config/routes.rb
Rails.application.routes.draw do
 
  resources :depository
  resources :products do 
    member do 
      put "add", to: "products#depository"
      put "remove", to: "products#depository"
    end
    
  end
  devise_for :users, controllers: { registrations: "registrations"}
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :costing, only:[:index]
  # Defines the root path route ("/")
  root "products#index"
  resources :subscriptions

  post '/subscriptions/create' => 'subscriptions#create'
  get '/subscriptions/landing' => 'subscriptions#show'

  #map.login '/users/sign_out', :controller => 'registrations', :action => 'new'
end

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light mb-3">
	<div class="container">
		<a class="navbar-brand" href="#"> Product Subscription App</a>
		<button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<%= link_to 'Home', root_path, class:'nav-link' %>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Products</a>
				</li>
				<% if admin? %>
				<li class="nav-item">
					<%= link_to 'New Product', new_product_path, class:'nav-link' %>
				</li>
				<% end %>
<!-- 				<%# if subscribed? %>
				<li class="nav-item">
					<%#= link_to depository_index_path, class:'nav-link' %>
				</li>
				<%# end %> -->
				<% if user_signed_in? %>
				<li class="nav-item"> <span>

				<%= link_to "Sign Out", destroy_user_session_path, class: 'nav-link', data: { "turbo-method": :delete } %>
				</li>

				<li class="nav-item"> <span><%= link_to "Account",
					edit_user_registration_path, class: 'nav-link' %> </span>
				</li>
				<% else %>
				<li class="nav-item">
					<a class="nav-link text-white" href="#"></a>
				</li>
				<li class="nav-item"> <span><%= link_to "Sign Up",
					new_user_registration_path, class: 'btn btn-primary' %> </span>
				</li>
				<li class="nav-item">
					<a class="nav-link text-white" href="#"></a>
				</li>
				<li class="nav-item"> <span><%= link_to "Sign In",
					new_user_session_path, class: 'btn btn-primary' %> </span>
				</li>			
				<% end %>
			</ul>
		</div>
	</div>
</nav>