config/routes.rb
Rails.application.routes.draw do
 
  resources :depository
  resources :products do 
    member do 
      put "add", to: "products#depository"
      put "remove", to: "products#depository"
    end
    
  end
  devise_for :users, controllers: { registrations: "registrations"}
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :costing, only:[:index]
  # Defines the root path route ("/")
  root "products#index"
  resources :subscriptions

  post '/subscriptions/create' => 'subscriptions#create'
  get '/subscriptions/landing' => 'subscriptions#show'

  #map.login '/users/sign_out', :controller => 'registrations', :action => 'new'
end

app/models/depository.rb
class Depository < ApplicationRecord
	attr_accessor :card_number, :card_cvv, :card_expires_month, :card_expires_year
	belongs_to :product
	belongs_to :user

	
def self.month_options
	Date::MONTHNAMES.compact.each_with_index.map { |name, i| ["#{i+1} - #{name}", i+1]}
end

def self.year_options
	(Date.today.year..(Date.today.year+10)).to_a
end

def process_payment
	customer = Stripe::Customer.create email: email, card: token
	Stripe::Charge.create customer: customer.id,
	amount: 1000,
	description: 'Premium',
	currency: 'usd'
end

end

app/controllers/depository_controller.rb
class DepositoryController < ApplicationController
	before_action :authenticate_user!

	def index
		@depository_products = current_user.depository_additions
		@user = current_user
	end

	def new
		#@depository = current_user.depository_additions
	end

	def create
	end
end

app/helpers/depository_helper.rb
module DepositoryHelper
end

app/views/depository/index.html.erb
<script>
  Stripe.setPublishableKey("<%= ENV['stripe_publishable_key'] %>");
</script>
<script type="text/javascript">
  $("#id_form_location").submit(function(event) {
  alert('it works');
});
</script>

<%= form_with url: "/subscriptions/create", method: :post do |p| %>
<%#= form_for(@depositories, url: depositories_path(resource), method: :post ,html: {class: 'cc_form'} do |p| %>
<%#= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |p| %>

<div class="row col-md-12">

<div class="form-group col-md-4 no-left-padding">

<%= p.label :card_number, "Card Number", data: { stripe: 'label'} %>

<%= p.text_field :card_number, class: "form-control", required: true, data: { stripe: 'number'} %>

</div>

<div class="form-group col-md-2">

<%= p.label :card_cvc, "Card CVC", data: { stripe: 'label'} %>

<%= p.text_field :card_cvv, class: "form-control", required: true, data: { stripe: 'cvv'} %>

</div>

<div class="form-group col-md-6">

<div class="col-md-12">

<%= p.label :card_expires, "Card Expires", data: { stripe: 'label'} %>

</div>

<div class="col-md-3">

<%= p.select :card_expires_month, options_for_select(Payment.month_options),

{ include_blank: 'Month' },

"data-stripe" => "exp-month",

class: "form-control", required: true %>

</div>

<div class="col-md-3">

<%= p.select :card_expires_year, options_for_select(Payment.year_options.push),

{ include_blank: 'Year' },

class: "form-control",

data: { stripe: "exp-year" }, required: true %>

</div>

</div>

</div>

<% end %>