config/routes.rb
Rails.application.routes.draw do
 
  resources :depository
  resources :products do 
    member do 
      put "add", to: "products#depository"
      put "remove", to: "products#depository"
    end
    
  end
  devise_for :users, controllers: { registrations: "registrations"}
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :costing, only:[:index]
  # Defines the root path route ("/")
  root "products#index"
  resources :subscriptions

  post '/subscriptions/create' => 'subscriptions#create'
  get '/subscriptions/landing' => 'subscriptions#show'

  #map.login '/users/sign_out', :controller => 'registrations', :action => 'new'
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader

	belongs_to :user
	has_many :depositories
	has_many :added_products, through: :depositories, source: :user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy depository]
  before_action :authenticate_user!, except: %i[ index show]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.build
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
  @product = current_user.products.build(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def depository
    type = params[:type]
    if type =="add"
      current_user.depository_additions << @product
      redirect_to depository_index_path, notice: "#{@product.title} was added to your depository"
    elsif type == "remove"
      current_user.depository_additions.delete(@product)
      redirect_to root_path, notice: "#{@product.title} was removed from your depository"
    else
      redirect_to product_path(@product), notice: "The product has not been added. Try once again"  
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :author, :image, :user_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

	def user_added_to_depository? user, product
		user.depositories.where(user: user, product: product).any?
	end
	
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>


 <div class="col-md-6">
            <div class="form-group">
           
            <%= f.input :title, require: true, input_html: { class: "form-control" }, wrapper: false, label_html: { class: "label text-dark" } %>
            <%= f.input :description, require: true, input_html: { class: "form-control" }, wrapper: false, label_html: { class: "label text-dark" } %>
            <%= f.input :author, require: true, input_html: { class: "form-control" }, wrapper: false, label_html: { class: "label text-dark" } %>
          

      
      <br>

          <label class="file-label">
          <%= f.input :image, as: :file, required: true, input_html: { class: "form-control" }, wrapper: false, label: false  %>
          
        </label>
           <br>
           <%= f.button :submit, class: "btn btn-dark" %>

      </div>

  </div>


<% end %>

app/views/products/_product.html.erb
<div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div class="card-body">

             
              <%= image_tag(product.image_url, class: 'card-img-top img-fluid') %>
                <h4 class="card-title"><%= product.title %></h4>
                <h6 class="card-subtitle text-muted"><%= product.author %></h6>



  <!-- SIMPLE CARD -->
          

                  <!-- if Subscribed -->
                  

                  <% if subscribed? %>

         



                     <div class="d-flex justify-content-between align-items-center">
                   <div class="btn-group">
                 
                    <% if user_added_to_depository?(current_user, product) %>

                <%= link_to 'Remove from Cart', add_product_path(product, type: "remove"), method: :put, class: "btn btn-danger" %>

                 <% if controller.controller_name == "depository" %>
                 <%= link_to 'Download', '#', class: "btn btn-success" %>
                  <% end %>

                  </div>

                </div>
               <!-- if Subscribed -->

                <% else %>
                  
                 <!-- Not Subscribed -->
                  
                   <%= link_to 'Add to Cart', add_product_path(product, type: "add"), method: :put, class: "btn btn-primary" %>

                  
             
               <% end %>

                <% else %>

               <div class="d-flex justify-content-between align-items-center">
                   <div class="btn-group">
               <%= link_to 'Add to Cart', new_user_registration_path, class: "btn btn-primary" %>
               <% end %>
               </div>

               </div>
              <!-- Not Subscribed -->
        
              </div>
              </div>
              </div>   



              

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<section class="jumbotron index">

   <div class="container">

   <h1 class="text-warning">Products</h1>
    <% if user_signed_in? && subscribed? %>
    <a href="#" class="btn btn-primary my-2">Dear <%= current_user.name %>! you already have a Subscription </a><br>
    <b> Keep watching for more updates!</b>

    <% elsif user_signed_in? && !subscribed? %>
    <p class="lead text-warning">Check out some of the latest Products</p>
    <a href="/subscriptions/new" class="btn btn-primary my-2"> Subscribe </a>

    <% else %>
    <p class="lead text-warning">Check out some of the latest Products</p>
    <a href="/subscriptions/new" class="btn btn-primary my-2"> Subscribe </a>
    <% end %>
   </div>

</section>

<section class="section">

   <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        
      <%= render @products %>

      </div>

    </div>

   </div>
</section>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @product.author %>
</p>


<p>
  <strong>Image:</strong>
  <%= @product.image %>
  <%= image_tag @product.image_url %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>